docs/api-documentation/V1.0/index.md

Refactoring the API versioning and release management section.

Refactored versioning section

---

docs/api-documentation/V1.0/index.md
docs/api-documentation/V1.0/json/geojson-swagger.json
docs/api-documentation/V1.0/json/lookup-swagger.json
docs/api-documentation/V1.0/json/reporting-swagger.json
docs/api-documentation/V1.0/json/work-swagger.json

Add swagger json files and documentation section

Add Swagger documentation section

---

docs/api-documentation/V1.1/json/lookup-swagger.json
docs/api-documentation/V1.1/json/reporting-swagger.json
docs/api-documentation/V1.1/json/work-swagger.json

Update v1.1 swagger docs with new endpoints/responses

Update v1.1 swagger docs 

---

docs/api-documentation/V1.1/index.md

**WIP until functionality is complete.**

SM-2601: Update polling endpoint docs with user exclusion field

---

docs/api-documentation/V1.3/index.md

Update user accounts and permissions table to include contractors and activities
Add a section for events and activities to the work api documentation
Add a section for object reference to the get history endpoint documentation

Update documentation for Street Smart sp 30

---

docs/api-documentation/V1.6/index.md

POST /works/updates
{
work_reference_number
update_date_time
+ update_id
}

Add additional variable in work update response

---

docs/api-documentation/V1.8/index.md
docs/api-documentation/V1.9/index.md
docs/api-documentation/index.html

Tidying up API Documentation index page.

Tidying up API Documentation index page.

---

docs/api-documentation/V1.11/index.md
docs/api-documentation/V1.12/index.md
docs/api-documentation/V1.13/index.md

The GET section 81 endpoint was incorrectly listed

Fix wrong path typo

---

docs/api-documentation/V1.13/json/work-swagger.json

Reverts departmentfortransport/street-manager-docs#217

Revert "SM-3979 - Add new optional properties promoter_status and promoter_st…"

---

docs/api-documentation/V1.16/index.md

Add HS2 filtering options from reporting API and added to release notes

Add HS2 search filtering to 1.16

---

docs/api-documentation/V1.16/index.md
docs/api-documentation/V1.17/index.md

Reflected in both V1.16 and V1.17 docs.

Added more detailed docs regarding the work history

---

docs/api-documentation/V1.17/index.md

SM-4472: Update documentation for access and permission details

---

docs/api-documentation/V1.18/index.md
docs/api-documentation/V1.18/json/work-swagger.json

Add town to release notes and work swagger json

---

docs/api-documentation/V1.18/index.md

https://streetmanager.atlassian.net/browse/SM-4832

SM-4832 docs update

---

docs/api-documentation/V1.19/index.md

Alter Audit message for FPNs

---

docs/index.html

Update index.html to include a link to service availability page

Update index.html to include a link to service availability page

---

.circleci/config.yml

Frontend - https://github.com/departmentfortransport/street-manager-frontend/pull/1473
API - https://github.com/departmentfortransport/street-manager-api/pull/800
GeoJSON API - https://github.com/departmentfortransport/street-manager-geojson-api/pull/173
Street Lookup API - https://github.com/departmentfortransport/street-manager-street-lookup-api/pull/132
Reporting API - https://github.com/departmentfortransport/street-manager-reporting-api/pull/275
Party API - https://github.com/departmentfortransport/street-manager-party-api/pull/150
Data Export API - https://github.com/departmentfortransport/street-manager-data-export-api/pull/46
Async Worker - https://github.com/departmentfortransport/street-manager-async-worker/pull/78
CSV Worker - …

feature/SM-5276 - CircleCI Pipelines

---

docs/api-documentation/V1.19/index.md

Add info on change to validity period end date calculation to "Versions and Changes" section

SM-4903: Add info on change to validity period end date calculation

---

docs/api-documentation/V1.22/index.md

API - https://github.com/departmentfortransport/street-manager-api/pull/819
Party API - https://github.com/departmentfortransport/street-manager-party-api/pull/156
Frontend - https://github.com/departmentfortransport/street-manager-frontend/pull/1504
Docs - https://github.com/departmentfortransport/street-manager-docs/pull/451

SM-5255: Add API updates for removing specific error messages

---

docs/api-documentation/V1.22/index.md

Client - https://github.com/departmentfortransport/street-manager-client/pull/271
API - https://github.com/departmentfortransport/street-manager-api/pull/823
Reporting client - https://github.com/departmentfortransport/street-manager-reporting-client/pull/111
Reporting API - https://github.com/departmentfortransport/street-manager-reporting-api/pull/285
Docs - https://github.com/departmentfortransport/street-manager-docs/pull/452

SM-5476: Add comments V2 updates to API docs

---

docs/api-documentation/V1.23/index.md

feature/SM-5485: Add documentation for upcoming comment topics

---

docs/api-documentation/V1.23/index.md

docs: https://github.com/departmentfortransport/street-manager-docs/pull/461
lookup api: https://github.com/departmentfortransport/street-manager-street-lookup-api/pull/138
lookup client: https://github.com/departmentfortransport/street-manager-street-lookup-client/pull/37

task/SM-5530: add note on new optional properties ASDResponse

---

docs/api-documentation/V1.23/index.md
docs/api-documentation/V1.24/index.md

feature/SM-3969: marking an asd as provided

---

docs/api-documentation/V1.25/index.md

Add docs for additional comment topics

SM-3716: Add additional comment topics

---

docs/api-documentation/V1.26/index.md
docs/api-documentation/json/event-notifier-message.json
docs/open-data/index.md

Example messages and property descriptions

SM-5488: Data Streaming documentation 

---

docs/open-data/index.md

notification message additional detail

SM-5488: Open data documentation 

---

docs/api-documentation/V1.26/index.md

Street lookup API - https://github.com/departmentfortransport/street-manager-street-lookup-api/pull/147
API - https://github.com/departmentfortransport/street-manager-api/pull/861
Frontend - https://github.com/departmentfortransport/street-manager-frontend/pull/1526
Street lookup API stable - https://github.com/departmentfortransport/street-manager-street-lookup-api-stable/pull/4
API stable - https://github.com/departmentfortransport/street-manager-api-stable/pull/4
Docs - https://github.com/departmentfortransport/street-manager-docs/pull/504

SM-4786: special_desig_description is now optional

---

docs/api-documentation/index.html

Grouped current/upcoming versions by environment

SM-6110: Update versions format to better reflect sandbox/prod differences

---

docs/api-documentation/json/event-notifier-message.json
docs/open-data/index.md

Update example open data notifications

feature/SM-6050: Update Open Data example notifications

---

docs/api-documentation/V1.25.5/index.md
docs/api-documentation/V2.5/index.md

Add documentation for account lockout

SM-3910: Add documentation for account lockout

---

docs/api-documentation/json/event-notifier-message.json
docs/open-data/index.md

1. Updated json schema to handle conditional fields for `object_data` depending on `object_type`. Can be tested here: https://www.jsonschemavalidator.net/
2. Added some missing fields to permit
3. Updated fields to use enum validation where appropriate

SM-6056: Update Open Data Docs - Activity Notifications

---

docs/api-documentation/V2.6/index.md

add additional offence_code filter param for reporting and data export apis to version and changes section

feature/SM-6146: docs updates

---

docs/_articles/disruptions-to-service-availability.md

https://github.com/departmentfortransport/street-manager-docs/pull/new/task/Update-Service-Availability-prod-service-deg-05-10-20

Update Service Availability page 05-10-20

---

docs/_articles/disruptions-to-service-availability.md

update service availibility page 0708-10-20

update service availibility page 0708-10-20

---

docs/api-documentation/V2.7/index.md

Add docs for link section 81 endpoint and audit events

SM-6195: Add docs for link section 81 endpoint and audit events

---

docs/api-documentation/V2.8/index.md

Add docs for unlink permit from section 81 endpoint

SM-6198: Add docs for unlink permit from section 81 endpoint

---

docs/api-documentation/V2.8/index.md

Add docs for work API enum string responses

SM-6284: Add docs for work API enum string responses

---

docs/api-documentation/index.html

Update current production version for sprint 16 release

SM-6504: Update current production version for sprint 16 release

---

docs/api-documentation/V2.10/index.md

feature/SM-6368: paginate work history docs updates

---

docs/api-documentation/V1.25.7/index.md
docs/api-documentation/V2.10/index.md
docs/api-documentation/index.html

feature/SM-6213: docs updates for reassigning section 81

---

docs/api-documentation/V1.25.7/index.md
docs/api-documentation/V2.10.1/index.md
docs/api-documentation/V2.9/index.md

Retrospectively adding the updated change request validation implemented in SM-6264.

SM-6264: Document updated change request validation

---

docs/api-documentation/V1.25.8/index.md

SM-6533: Add optional property to Section81Response

---

docs/api-documentation/V2.10.2/index.md

feature/SM-5733: filter by workstream docs updates

---

docs/api-documentation/V2.10.4/changelog.md

Add sample inspection reporting endpoint query param updates

SM-5178: Add sample inspection reporting endpoint query param updates

---

docs/api-documentation/V1.25.9/changelog.md
docs/api-documentation/V2.10.4/changelog.md

Documentation for get files error response updates

feature/SM-6605: docs updates

---

docs/api-documentation/V1.25.10/changelog.md
docs/api-documentation/V2.10.5/changelog.md

Also fixed some typos raised by a spell checker

SM-3950: Document Reassign Section 81 auditing update

---

docs/api-documentation/V1.25.11/changelog.md
docs/api-documentation/V2.10.6/changelog.md

Update docs for GeoJSON API restrictions

SM-6679: Update docs for GeoJSON API restrictions

---

docs/api-documentation/V2.10.7/changelog.md

docs updates to reflect organisation status and organisation status string properties being added to user and organisation responses

feature/SM-6813: organisation status docs updates

---

docs/_articles/charges.md
docs/_layouts/article.html
docs/_layouts/default.html
docs/registration/index.md

add charges article with table of charges and update registration page

SM-7015: Update Registration page

---

docs/api-documentation/versions-and-changes/v1/changelog.md
docs/api-documentation/versions-and-changes/v2/changelog.md

Update change log for v1 and v2 to change the logic for deadline date of PA

SM-6393/Docs update for updating PA response period logic

---

docs/terms.html

This is to update the terms and conditions for street manager

SM-7058: update terms of service

---

docs/_includes/api-documentation/v2/resource-guide.md
docs/_includes/api-documentation/v3/resource-guide.md
docs/api-documentation/index.html
docs/api-documentation/versions-and-changes/v2/changelog.md
docs/api-documentation/versions-and-changes/v3/changelog.md

Remove hourly permit export references

SM-6097: Remove hourly permit export references

---

docs/_includes/api-documentation/v3/access-and-permissions.md
docs/api-documentation/versions-and-changes/v2/changelog.md
docs/api-documentation/versions-and-changes/v3/changelog.md

Added a new Role `Street Works Administrator` and add an explanation of the role

SM-7071: add Street works admin to list of roles and explain role

---

docs/_articles/disruptions-to-service-availability.md

Updating service disruption page with 1st june production intermittent outage

Add june 1st release outages, remove IE issue notification

---

docs/registration/index.md

This is to capture the information when contractors sign up.

SM-7237: add Company house number to email template

---

docs/offline/index.md

Updating offline guidance page in line with https://streetmanager.atlassian.net/browse/SM-7361

SM7361 update offline guidance

---

docs/release-calendar/index.md

Removing previous releases following sandbox release on 08/07/21

Update release calendar 09/07/21

---

docs/_articles/disruptions-to-service-availability.md

Add following entry:
24/06/21 13:40-14:10 Sandbox environment unavailable for 30 mins due to planned release.

Update service availability with sandbox downtime
